- hosts: all
  gather_facts: no
  tasks:
    #- shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5
    - shell: ps -ef f | grep mingetty | grep -v grep
      register: ps

    - debug: var=ps.stdout_lines
